//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KelimeOgretici
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KelimeOgreticiEntities3 : DbContext
    {
        public KelimeOgreticiEntities3()
            : base("name=KelimeOgreticiEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Gun1> tbl_Gun1 { get; set; }
        public virtual DbSet<tbl_Gun180> tbl_Gun180 { get; set; }
        public virtual DbSet<tbl_Gun30> tbl_Gun30 { get; set; }
        public virtual DbSet<tbl_Gun7> tbl_Gun7 { get; set; }
        public virtual DbSet<tbl_GunListesi> tbl_GunListesi { get; set; }
        public virtual DbSet<tbl_KelimeListesi> tbl_KelimeListesi { get; set; }
    }
}
