//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KelimeOgretici
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GunListesi
    {
        public int id { get; set; }
        public string gun1 { get; set; }
        public string gun7 { get; set; }
        public string gun30 { get; set; }
        public string gun180 { get; set; }
    }
}
