//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KelimeOgretici
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Gun7
    {
        public int id { get; set; }
        public string ingilizcekelime { get; set; }
        public string turkcekelime { get; set; }
    }
}
